/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadora;

public class App {
    
    /** 
     * @author Douglas Machado
     * @version 1.2
     * @since Realease 1.0 da aplicação
     * @param args
     */
    public static void main(String[] args) {
        calculadora.Soma.Teste soma = new calculadora.Soma.Teste();
        soma.teste();
        calculadora.Divisao.Teste divisao = new calculadora.Divisao.Teste();
        divisao.teste();
        calculadora.Multiplicacao.Teste multiplicacao = new calculadora.Multiplicacao.Teste();
        multiplicacao.teste();
        calculadora.Subtracao.Teste subtracao = new calculadora.Subtracao.Teste();
        subtracao.teste();
    }
}
